[workspace]
members = [
    "parser",
    "ast",
    "compiler",
    "compiler-bin"
]

resolver = "2"

[workspace.package]
rust-version = "1.89"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Satyam Jay"]
