[package]
name = "frameql-parser"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
frameql-ast = { path = "../ast" }
pest = "2.8.1"
pest_derive = "2.8.1"
